const USER_DATA = "USER_DATA";
const BOOKING_FORM_STEP = "BOOKING_FORM_STEP";
const HOTELS_RESERVED_LIST = "HOTELS_RESERVED_LIST";
const HOTELS = "HOTELS";
const THEME = "THEME";

export { USER_DATA, BOOKING_FORM_STEP, HOTELS_RESERVED_LIST, HOTELS, THEME };
